# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShobaikLobaik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CryptoSwift'
  pod 'Alamofire'
  pod 'MBProgressHUD'
end
