# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clown' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clown
pod 'ImageSlideshow'
end
